# Service registers under this name
# Control the InternalResourceViewResolver:
spring:
  application:
    name: BMA-service-API

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.110.51:1111/eureka/

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
enabled: false

server:
  port: 1112